In [1]:
import os
os.chdir(os.getcwd())
os.getcwd()

'/Users/pantchanit/Documents/python-nonlinear'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline

In [3]:
df = pd.read_csv("challenger.csv")
df.head()

Temp Failure  Failure1
0    53       Y         1
1    57       Y         1
2    58       Y         1
3    63       Y         1
4    66       N         0

## StatModels

In [4]:
df.columns

Index(['Temp', 'Failure', 'Failure1'], dtype='object')

In [5]:
import statsmodels.api as sm
X = df[['Temp']]
X = sm.add_constant(X, prepend=False)
X.head()

/Users/pantchanit/opt/anaconda3/lib/python3.9/site-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


Temp  const
0    53    1.0
1    57    1.0
2    58    1.0
3    63    1.0
4    66    1.0

In [6]:
y = df['Failure1']

In [7]:
import statsmodels.discrete.discrete_model as sd
model = sd.Logit(y, X)
result = model.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.441635
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Failure1   No. Observations:                   23
Model:                          Logit   Df Residuals:                       21
Method:                           MLE   Df Model:                            1
Date:                Thu, 27 Jan 2022   Pseudo R-squ.:                  0.2813
Time:                        11:23:39   Log-Likelihood:                -10.158
converged:                       True   LL-Null:                       -14.134
Covariance Type:            nonrobust   LLR p-value:                  0.004804
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Temp          -0.2322      0.108     -2.145      0.032      -0.444      -0.020
const         15.0429      7.379      2.039      0.041       0.581      29.505
==============================================================================
"""

In [8]:
result.params

Temp     -0.232163
const    15.042902
dtype: float64

## Scikitlearn

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [10]:
# lecture example uses all data to train (test_size=0.0).
# typically, test_size is set to be 0.30

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=99)

In [11]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [12]:
model.coef_

array([[-1.91390846e-01, -2.48986195e-07]])

In [13]:
model.intercept_

array([12.25603115])

In [14]:
# lecture example uses all data to train
# typically use X_test to do prediction

predictions = model.predict(X_train)
predictions

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [15]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix 

print(confusion_matrix(y_train,predictions))

[[14  0]
 [ 3  3]]


In [16]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix 

print(classification_report(y_train, predictions))

              precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.50      0.67         6

    accuracy                           0.85        20
   macro avg       0.91      0.75      0.78        20
weighted avg       0.88      0.85      0.83        20



In [17]:
my_data = {'Temp': [77],
          'const': [1.0]}
my_df = pd.DataFrame(my_data, columns=['Temp', 'const'])
my_df 

Temp  const
0    77    1.0

In [18]:
predictions = model.predict(my_df)
predictions

array([0])